apiVersion: v1
kind: PersistentVolume
metadata:
  name: jsppv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce # Or ReadOnlyMany, ReadWriteMany if applicable
  awsElasticBlockStore:
    volumeID: #id
    fsType: ext4
    availabilityZone: #az
  persistentVolumeReclaimPolicy: Retain # Or Recycle, Delete
